services:
  hfsslive:
    container_name: hfsslive
    image: hfsslive:latest
    env_file:
      - ./.env
    environment:
      - PROD=True
      - GPS_TCP_ENABLED=false  # Disabled - using separate GPS service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5012:8000
      # GPS port handled by separate gps-tcp-server service
    command: ['uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '8000']
    volumes:
      - logs:/app/logs
      - static:/app/static
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"        # Max size per log file
        max-file: "5"           # Keep 5 rotated files
        compress: "true"        # Compress rotated files
  
  # Separate GPS TCP Server service
  # ACTIVATED: GPS TCP server runs as separate service
  
  gps-tcp-server:
    container_name: gps-tcp-server
    image: gps-tcp-server:latest
    env_file:
      - ./.env
    environment:
      - PROD=True
      - GPS_TCP_HOST=0.0.0.0
      - GPS_TCP_PORT=${GPS_TCP_PORT:-9090}
      - GPS_TCP_ENABLED=true
      # With host network, Redis is on localhost
      - REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0
    build:
      context: .
      dockerfile: ./tcp_server/Dockerfile
    # Use host network to see real client IPs
    network_mode: host
    volumes:
      - gps-logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        compress: "true"

volumes:
  logs:
  static:
  gps-logs:  # Volume for separate GPS service

networks:
  app-network:
    external: true
    name: app-network
