services:
  hfsslive:
    container_name: hfsslive
    image: hfsslive:latest
    env_file:
      - ./.env
    environment:
      - PROD=True
      # Set GPS_TCP_ENABLED=false when using separate GPS service
      # Set GPS_TCP_ENABLED=true for embedded mode (default)
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5012:8000
      # Only expose GPS port if running embedded mode
      - "${GPS_TCP_PORT}:${GPS_TCP_PORT}"
    command: ['uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '8000']
    volumes:
      - logs:/app/logs
      - static:/app/static
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"        # Max size per log file
        max-file: "5"           # Keep 5 rotated files
        compress: "true"        # Compress rotated files
  
  # Optional: Separate GPS TCP Server service
  # Uncomment below to run GPS TCP server as separate service
  # Remember to set GPS_TCP_ENABLED=false in .env for hfsslive service
  
  # gps-tcp-server:
  #   container_name: gps-tcp-server
  #   image: gps-tcp-server:latest
  #   env_file:
  #     - ./.env
  #   environment:
  #     - PROD=True
  #     - GPS_TCP_HOST=0.0.0.0
  #     - GPS_TCP_PORT=${GPS_TCP_PORT:-9090}
  #     - GPS_TCP_ENABLED=true
  #     # With host network, Redis is on localhost
  #     - REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0
  #   build:
  #     context: .
  #     dockerfile: ./tcp_server/Dockerfile
  #   # Use host network to see real client IPs
  #   network_mode: host
  #   volumes:
  #     - gps-logs:/app/logs
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "50m"
  #       max-file: "3"
  #       compress: "true"

volumes:
  logs:
  static:
  # gps-logs:  # Uncomment when using separate GPS service

networks:
  app-network:
    external: true
    name: app-network
