"""introduing cascade delete

Revision ID: 2589d3077d07
Revises: 
Create Date: 2025-01-26 19:37:11.044607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2589d3077d07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id')
    )
    op.create_index('idx_race_id', 'races', ['race_id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.String(), nullable=False),
    sa.Column('race_uuid', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('pilot_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('first_fix', sa.JSON(), nullable=True),
    sa.Column('last_fix', sa.JSON(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_uuid'], ['races.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flight_ids', 'flights', ['race_id', 'pilot_id'], unique=False)
    op.create_index('idx_flight_source', 'flights', ['flight_id', 'source'], unique=True)
    op.create_table('live_track_points',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_uuid', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.Column('elevation', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['flight_uuid'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datetime', 'id'),
    sa.UniqueConstraint('flight_id', 'lat', 'lon', 'datetime', name='live_track_points_unique_parent')
    )
    op.create_index('idx_live_track_points_datetime_flight', 'live_track_points', ['datetime', 'flight_uuid'], unique=False)
    op.create_table('uploaded_track_points',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_uuid', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.CHAR(length=100), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.Column('elevation', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['flight_uuid'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datetime', 'id'),
    sa.UniqueConstraint('flight_id', 'lat', 'lon', 'datetime', name='uploaded_track_points_unique_parent')
    )
    op.create_index('idx_uploaded_track_points_datetime_flight', 'uploaded_track_points', ['datetime', 'flight_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uploaded_track_points_datetime_flight', table_name='uploaded_track_points')
    op.drop_table('uploaded_track_points')
    op.drop_index('idx_live_track_points_datetime_flight', table_name='live_track_points')
    op.drop_table('live_track_points')
    op.drop_index('idx_flight_source', table_name='flights')
    op.drop_index('idx_flight_ids', table_name='flights')
    op.drop_table('flights')
    op.drop_index('idx_race_id', table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
