"""removing char

Revision ID: 282ecfd217b3
Revises: 9e5fec69ad97
Create Date: 2025-01-22 16:08:36.658680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282ecfd217b3'
down_revision: Union[str, None] = '9e5fec69ad97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'flight_id',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('live_track_points', 'flight_id',
               existing_type=sa.CHAR(length=100),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_track_points', 'flight_id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=100),
               existing_nullable=False)
    op.alter_column('flights', 'flight_id',
               existing_type=sa.String(),
               type_=sa.CHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
