"""first creation

Revision ID: 2f575d65e4e6
Revises: 
Create Date: 2025-01-22 14:59:29.426772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f575d65e4e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.CHAR(length=100), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('flight_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flight_ids', 'flights', ['race_id', 'pilot_id'], unique=False)
    op.create_index('uq_flight_id_source', 'flights', ['flight_id', 'source'], unique=True)
    op.create_table('live_track_points',
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_uuid', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.Column('elevation', sa.Float(precision=53), nullable=True),
    sa.Column('speed', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['flight_uuid'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('datetime', 'id')
    )
    op.create_index('idx_live_track_points_datetime_flight', 'live_track_points', ['datetime', 'flight_uuid'], unique=False)
    op.create_table('uploaded_track_points',
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_uuid', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.Column('elevation', sa.Float(precision=53), nullable=True),
    sa.Column('speed', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['flight_uuid'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('datetime', 'id')
    )
    op.create_index('idx_uploaded_track_points_datetime_flight', 'uploaded_track_points', ['datetime', 'flight_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uploaded_track_points_datetime_flight', table_name='uploaded_track_points')
    op.drop_table('uploaded_track_points')
    op.drop_index('idx_live_track_points_datetime_flight', table_name='live_track_points')
    op.drop_table('live_track_points')
    op.drop_index('uq_flight_id_source', table_name='flights')
    op.drop_index('idx_flight_ids', table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
