"""introducing new index to avoid duplicates

Revision ID: 6f78764f45ec
Revises: 282ecfd217b3
Create Date: 2025-01-24 18:04:16.130365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f78764f45ec'
down_revision: Union[str, None] = '282ecfd217b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_track_point', 'live_track_points', ['flight_id', 'lat', 'lon', 'datetime'], unique=True)
    op.create_index('idx_unique_uploaded_track_point', 'uploaded_track_points', ['flight_id', 'lat', 'lon', 'datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_uploaded_track_point', table_name='uploaded_track_points')
    op.drop_index('idx_unique_track_point', table_name='live_track_points')
    # ### end Alembic commands ###
