"""reputting flight_id

Revision ID: 9e5fec69ad97
Revises: 2f575d65e4e6
Create Date: 2025-01-22 15:16:18.376457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5fec69ad97'
down_revision: Union[str, None] = '2f575d65e4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_track_points', sa.Column('flight_id', sa.CHAR(length=100), nullable=False))
    op.drop_index('live_track_points_datetime_idx', table_name='live_track_points')
    op.add_column('uploaded_track_points', sa.Column('flight_id', sa.CHAR(length=100), nullable=False))
    op.drop_index('uploaded_track_points_datetime_idx', table_name='uploaded_track_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uploaded_track_points_datetime_idx', 'uploaded_track_points', [sa.text('datetime DESC')], unique=False)
    op.drop_column('uploaded_track_points', 'flight_id')
    op.create_index('live_track_points_datetime_idx', 'live_track_points', [sa.text('datetime DESC')], unique=False)
    op.drop_column('live_track_points', 'flight_id')
    # ### end Alembic commands ###
