"""adding unique constraint

Revision ID: a1bda9eda0cd
Revises: 6f78764f45ec
Create Date: 2025-01-24 19:39:36.395008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bda9eda0cd'
down_revision: Union[str, None] = '6f78764f45ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_track_point', table_name='live_track_points')
    op.create_unique_constraint('live_track_points_unique_parent', 'live_track_points', ['flight_id', 'lat', 'lon', 'datetime'])
    op.drop_index('idx_unique_uploaded_track_point', table_name='uploaded_track_points')
    op.create_unique_constraint('uploaded_track_points_unique_parent', 'uploaded_track_points', ['flight_id', 'lat', 'lon', 'datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uploaded_track_points_unique_parent', 'uploaded_track_points', type_='unique')
    op.create_index('idx_unique_uploaded_track_point', 'uploaded_track_points', ['flight_id', 'lat', 'lon', 'datetime'], unique=True)
    op.drop_constraint('live_track_points_unique_parent', 'live_track_points', type_='unique')
    op.create_index('idx_unique_track_point', 'live_track_points', ['flight_id', 'lat', 'lon', 'datetime'], unique=True)
    # ### end Alembic commands ###
